### ISSUE TITLE
256x256 SD models

### ISSUE THREAD

**Issue by ClashSAN** [liuliu/swift-diffusion#13]
hi, I was wondering if you've seen this model which (may?) be useful to devices with a smaller memory size. https://huggingface.co/justinpinkney/miniSD
My 3gb ipad will crash at the lowest size.

Also, thank you for your lengthy readme, it was interesting to read your experience. I am already interested in model conversion to various formats: Openvino IR format, Jax, ONNX,
but specifically I want to what I can improve the cpu only experience. I've only been seeing the openvino besdev repo performing ok results at 8-10 steps. [Someone apparently enabled DDIM](https://github.com/Drake53/stable_diffusion.openvino/commit/a56987c6bb1b8500e8662f3666d042bbdbd5296c) through diffusers library, but something is wrong, and most pictures produce visible whiteish outlines. Do you have some recommendations on how to fix this? If DDIM sampler works ok, perhaps I'll eventually figure out how to use this [conversion script for IR format ](https://huggingface.co/ShadowPower/waifu-diffusion.openvino/discussions/1) to convert cooler models

**Comment by liuliu** [comment]
TBH, none of these samplers are hard, I would just implement these samplers myself to see if there are any weirdness with openvino. I have some sample code throw around, for PLMS, just check here: https://github.com/liuliu/swift-diffusion/blob/liu/nhwc/examples/txt2img/main.swift#L146, for DDIM, check this: https://github.com/liuliu/swift-diffusion/blob/liu/unet/examples/txt2img/main.swift#L206 and also see the commented out code for DPM++ Karras as well as Euler A.

For miniSD, yeah, it is interesting, I will integrate next week, but I doubt it will help 3GiB since the model seems crash when loading the weights (1.6GiB), but we can give it a try after integration (mainly interested in this as it can go really fast, probably 5~10s on iPhone).

**Comment by ClashSAN** [comment]
Thank you very much!

>mainly interested in this as it can go really fast, probably 5~10s on iPhone

Really nice. 

I see. currently Draw Things does its lowest at 384x384, so I also thought a lower size generation may help, but that's not it, it's the model being loaded
