### ISSUE TITLE
Bug in sdxl_txt2img example

### ISSUE THREAD

**Issue by ghost** [liuliu/swift-diffusion#52]
To reproduce:
1) Fresh clone on M1 mac
2) Change the WORKSPACE etc, acc to readme 
3) Download all models from https://static.libnnc.org/<model_name> and replace the hardcoded model paths 
4) `bazel run examples:sdxl_txt2img  --compilation_mode=opt`

I get this image:
![txt2img](https://github.com/liuliu/swift-diffusion/assets/126301759/f7cfbbf8-678a-43c5-b162-dc7325caed25)

**Comment by ghost** [comment]
Any idea what is going on? I feel some channel ordering thing. Something is getting reshaped in a wrong way.

**Comment by liuliu** [comment]
The code should work with CUDA. On Mac, you need to turn off MFA (because its batched GEMM implementation expects NHWC layout).

```swift
DynamicGraph.flags = [.disableMetalFlashAttention]
```

**Comment by ghost** [comment]
![txt2img](https://github.com/liuliu/swift-diffusion/assets/126301759/8f25c256-2a0a-48de-aff3-f6c48b7c79ce)
This is the output i get when i do that.

**Comment by liuliu** [comment]
That's weird. The code worked for me on NVIDIA platforms (as you can see, I repurposed the code to run SSD-1B models). You might want to use `--compilation_mode=dbg` so if there are any assertions, it is triggered first.

Also double check the models are all exist. I checked the code in the repo, one of the clip encoder uses `clip_vit_l14_f32.ckpt` rather than f16 variant available, might need to change the path a little bit (although not sure if clip encoder messed would result this image or not)

**Comment by ghost** [comment]
Right that was it, thanks
